"""
Django settings for pharmacy project.

Generated by 'django-admin startproject' using Django 3.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve(strict=True).parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '1%#4)%cu&52e(^mt8ite2t76pek0bz6qdx!c^a#s%gt@)7482z'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'category',
    'accounts',
    'store',
    'carts',
    'orders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pharmacy.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['index'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'category.context_processors.menu',
                'carts.context_processors.counter',
            ],
        },
    },
]

WSGI_APPLICATION = 'pharmacy.wsgi.application'

AUTH_USER_MODEL = 'accounts.Account'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR /'static'

STATICFILES_DIRS = [
    'pharmacy/static',
]

#MEDIA File Configuration
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR /'media'


JAZZMIN_SETTINGS = {
    # Links to put along the top menu
    "topmenu_links": [

        # Url that gets reversed (Permissions can be added)
        {"name": "Dashboard",  "url": "http://127.0.0.1:8000/admin", "permissions": ["auth.view_user"]},
        {"name": "Account",  "url": "http://127.0.0.1:8000/adminaccounts/account/", "permissions": ["auth.view_user"]},
        {"name": "Category",  "url": "http://127.0.0.1:8000/admincategory/category/", "permissions": ["auth.view_user"]},
        {"name": "Store",  "url": "http://127.0.0.1:8000/adminstore/product/", "permissions": ["auth.view_user"]},
        {"name": "Carts",  "url": "http://127.0.0.1:8000/admincarts/cart/", "permissions": ["auth.view_user"]},
        {"name": "CartItem",  "url": "http://127.0.0.1:8000/admincarts/cartitem/", "permissions": ["auth.view_user"]},
        {"name": "Payment",  "url": "http://127.0.0.1:8000/adminorders/payment/", "permissions": ["auth.view_user"]},
        {"name": "Order",  "url": "http://127.0.0.1:8000/adminorders/order/", "permissions": ["auth.view_user"]},
        {"name": "Order Product",  "url": "http://127.0.0.1:8000/adminorders/orderproduct/", "permissions": ["auth.view_user"]},
    ],
    
    # Title on the brand (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_brand": "Admin Panel",
}

JAZZMIN_UI_TWEAKS = {
    "theme": "darkly",
}

from django.contrib.messages import constants as messages
MESSAGE_TAGS = {
    messages.ERROR: 'danger',
}


#SMTP Server Configuration
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'bibekniroula3@gmail.com'
EMAIL_HOST_PASSWORD = 'holaspain@77'
EMAIL_USE_TLS = True